name: moka_store
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  dartz: ^0.10.1
  equatable: ^2.0.5
  get_it: ^7.2.0
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  carousel_slider: ^4.1.1
  google_fonts: ^3.0.1
  shimmer: ^2.0.0
  cached_network_image: ^3.2.2
  animate_do: ^2.1.0
  lottie: ^1.4.3
  flutter_overboard: ^3.1.1
  shared_preferences: ^2.0.15
  fluttertoast: ^8.0.9
  flutter_zoom_drawer: ^3.0.3
  flutter_svg: ^1.1.5
  flutter_rating_bar: ^4.0.1
  readmore: ^2.2.0
  sqflite: ^2.1.0
  flutter_launcher_icons: ^0.10.0
  webview_flutter: ^3.0.4
  rounded_loading_button: ^2.1.0

  #firebase
  firebase_core: ^1.22.0
  cloud_firestore: ^3.4.8


dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/fruit-shop.png"

  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/market.json
    - lang/ar.json
    - lang/en.json

  fonts:
    - family: IconBroken
      fonts:
        - asset: assets/icons/icons.ttf
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Raleway-Medium.ttf
          weight: 500
        - asset: assets/fonts/Raleway-Regular.ttf
          weight: 400
        - asset: assets/fonts/Raleway-Light.ttf
          weight: 300